name = "esphome-pr-bot"
main = "src/index.js"
compatibility_date = "2024-03-26"
compatibility_flags = ["nodejs_compat"]
find_additional_modules = true


[observability.logs]
enabled = true


[[kv_namespaces]]
binding = "GITHUB_TOKENS"
id = "75b765190cf444b3b66d0feedaf942b0"
